[project]
name = "simple-graphics-lib"
version = "0.0.11"
authors = [
  { name="Max-Hillyer", email="maxhillyer7012@gmail.com" },
]
dependencies = [
    "pygame",
]
description = "A simple graphics library for python learners"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/Max-Hillyer/Simple_graphics"
Issues = "https://github.com/Max-Hillyer/Simple_graphics/issues"